### ISSUE TITLE
Gravity vector, coordinate system, handed-ness

### ISSUE THREAD

**Issue by apsabelhaus** [uqLab/stedy#10]
Currently, the documentation assumes a direction for its coordinate system, but I can't actually tell which axes go where. Answering the following questions in the documentation / user guide would be helpful.

1. Which direction is gravity assumed to act in, in the generic case? Your other examples include it as the third coordinate, but I'm unsure if that's assumed in general (example, if I was to add gravity to the Dbar example, what's "down?")

2. What is the coordinate system for your axes? Is there a frame that can be imposed on one of the images?

3. As a result, I can’t actually tell your node numbering in the example (Template_Dbar). Which nodes are which?

However, one significant potential question about the underlying coordinate system is its handed-ness. It would be worth addressing the following question relatively thoroughly.

4. The Dbar example seems to use the first and third coordinates for the in-plane example. Using “z” as “vertical” in two dimensions, with positive numbers in the first coordinate being "to the right of the origin", might actually imply a left-handed coordinate system – I’ve come across this issue in my own work, where keeping a right-handed coordinate system requires gravity in -z in three dimensions but -y in two dimensions. A left-handed system is fine, that’s what's used in Bullet Physics underlying NTRTsim, but that's a numerical solver instead of an analytic solution. This may have significant implications for the cross-products in Lagrange’s equations and should be discussed explicitly, especially if the handedness accidentally changes between the 2D and 3D case.

**Comment by vaishnavtv** [comment]
1. Gravity is assumed to be in the negative z direction in the examples we have considered. 
2. We have adopted the Cartesian coordinate system. The User guide describes how to define the nodal coordinate matrix N as well as the gravity vector. 
3. We considered adding an automatic node numbering routine to the plot_configuration function, but it was aesthetically not a pleasant feature on the final image/plot. We believe that the user, when defining his structure's geometry will be cognizant of the node indexing prior to simulation. If you would still like us to attach node numbers to the configuration plot, we would be happy to do so. 
4. The gravity vector being vertically downward in the animations is simply to facilitate an easier viewing. The right handedness of the system is not affected by how we view the final results of the simulation. Please let me know if I have addressed your query.

**Comment by apsabelhaus** [comment]
Thanks @vaishnavtv . To each of your points - 

1 + 2) This makes sense, but what I'm unclear about is the exact orientation of your coordinate frame. It's Cartesian coordinates, but which of x/y/z are up/down/left/right? Providing a set of axes somehow would really clarify things, particularly if your examples are different projections. It would then also be worth saying this in your User Guide somehow - "STEDY is designed to be used with any orientation of gravity, but these examples have gravity in the -z direction, with the coordinate frame shown in figure (SOMETHING)"

3) No need to put the node numbers on the plot, just some way to know which is which. As in the comment for 1+2, since there are no axes / no orientation of the coordinate frame specified, I can't really tell which of the nodes in the picture correspond to which columns of N. If you somehow had arrows for +x, +z, etc., then it would be easy to tell which is which. If this is a bit of a mess to do in MATLAB, you could manually add a coordinate frame to one of the figures in your User Guide.

4) This might be addressed by giving axes somehow on the plot. It's still unclear to me which 2D projection we're looking at. Example - is the structure "flat" with gravity pointing "to the side", or is the structure "standing up" with gravity pointing "down"?

Thanks for the clarifications.

**Comment by vaishnavtv** [comment]
@apsabelhaus, I have attempted to attach a coordinate frame to the plot_configuration function. Kindly test the example files and let me know if that was what you were looking for.

**Comment by vaishnavtv** [comment]
@apsabelhaus , I'm seeing this image when I run plot_configuration.m and rotate in 3D. Could you tell me if you're updating the AZ and EL (azimuth and elevation) inputs when you're testing this function?
![dbar_axes](https://user-images.githubusercontent.com/8902316/50228627-6ee29480-03ce-11e9-8b95-8270535bbad7.jpg)

**Comment by apsabelhaus** [comment]
@vaishnavtv, that's exactly what's happening on my end, thanks for catching that. Looking at the structure with a negative elevation makes it look like a positive elevation with the axis in the wrong direction. I rotated the figure more and convinced myself that you've got the right coordinate system. I'm going to close this issue and leave it here for others if they come across the same confusion. I appreciate the effort to help me confirm what your code was doing.

If you all do edit the plotting function in the future, I'd recommend a fix so that the elevation doesn't accidentally distort the view for your users.
