### ISSUE TITLE
Non-standard connectivity matrix

### ISSUE THREAD

**Issue by apsabelhaus** [uqLab/stedy#12]
The connectivity matrix used in STEDY currently places the bars before the cables: [Cb; Cs]. 

Usually, it's done the other way around, [Cs; Cb], in the form-finding literature for tensegrities. See for example, Tran and Lee 2010, Advanced Form-Finding of Tensegrity Structures. I believe Skelton does it this way in his book, as does Motro, and Sultan, and Mirats-Tur.

Not a big deal, just worth noting so people don't accidentally make mistakes when coming in to use your software.

**Comment by vaishnavtv** [comment]
Oh, I wasn't familiar about other conventions. We have followed the standard adopted in Skelton's book, i.e., [Cb; Cs]. Thank you.
