### ISSUE TITLE
Discussion of limitations

### ISSUE THREAD

**Issue by apsabelhaus** [uqLab/stedy#13]
This is a minor point, and might just be my misunderstanding, so please correct me or point to a place this is discussed.

All the structures and examples in STEDY use bars that are pinned with respect to each other. But, that doesn't actually cover all tensegrity structures, and doesn't actually cover even type-1 structures. There are some robots where the bars are rigidly attached in groups and don't move with respect to each other, but still move in the world frame. See for example Friesen's 2014 ICRA paper, Brian Mirletz' 2015 papers in IROS and Soft Robotics, or my own ACC 2017 paper on a tensegrity spine robot.

A traditional example of such a structure is Snelson's "X-Cross" in chapter 1 of Skelton's book.

Is there a way to capture this behavior in your system? Example, is it possible to pin a joint in all 3 degrees of freedom so it becomes built-in but still moves freely? Does STEDY have the ability to do the X-cross?

If not - again, that's fine, it should just be noted that this is a limitation. The software is very extensive as it is, and is a great contribution to the community.

**Comment by addyhsu** [comment]
We actually cover class-1 structures. Please see the ball example where all bars are not connected but 3 nodes are pinned on the ground. 

For different shapes of bars, our software in the first version does not consider these configurations. If a special structure is needed, one can consider the specific shape as extra constraints and modify the nonlinear constraints in the core code, although we do not encourage users to do it. We will add this feature in the next version.

**Comment by vaishnavtv** [comment]
Thank you for raising this issue, @apsabelhaus. I was personally not aware of such structures being used in conventional tensegrity frameworks. The formulation implemented in STEDY allows for structures of the kind you're speaking about by introducing further non-linear constraints, but the software is not equipped with an automated feature of with such functionality at the moment. We will definitely attempt to incorporate such systems in future versions of the software. 
I will mention this in the User Guide for now.

**Comment by apsabelhaus** [comment]
Thanks all. To each point - 

@addyhsu There might be a misunderstanding of definitions here. Take a look at Ch. 1 of the Skelton book, the figure of the Snelson "X". I know it's a bit of a nuisance to consider class 1 structures being both "bars only" and "bars rigidly connected to other bars", and Skelton himself abuses the term, but it actually becomes a big deal sometimes, like in all those papers I mentioned. The ball example actually doesn't represent the kinds of class 1 structures I was mentioning. Again, not a big deal, but when figuring out, should be mentioned.

@vaishnavtv Completely understandable! People often use the term "tensegrity" to be synonymous with what you've got in STEDY, so it might be more of a technical definition difference than anything. And again, it doesn't detract from your software in any way that it isn't able to handle this case just yet. Let me know when you have a chance to put the mention in the User Guide and that will really be all that's needed to close this comment. Thanks.

**Comment by vaishnavtv** [comment]
I have added a Note to the Introduction part of the User Guide addressing this. Please let me know if it addresses your query satisfactorily.

**Comment by addyhsu** [comment]
@apsabelhaus Thanks for the reply. It's like I misunderstood the meaning of class 1 structures. Anyway, Our code can model any shapes that you mentioned before, but at this time users cannot do it easily. We will need some extra connectivity matrices and nonlinear constraints, which will look like bar length constraints, to simulate those structures. This is a very good comment that we will take care of it soon.

**Comment by vaishnavtv** [comment]
@apsabelhaus, please let us know if the revisions in the documentation are satisfactory.

**Comment by apsabelhaus** [comment]
Yes, the comment is sufficient, and perfectly helpful. thanks for adding.
