### ISSUE TITLE
Error in examples Arm.m and Ball.m

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [uqLab/stedy#4]
After entering the time-step (I entered 0.01) I get the following error message for the example `Arm.m` and `Ball.m`:

```none
Error using odearguments (line 21)
When the first argument to ode45 is a function handle, the tspan argument must have at least two elements.

Error in ode45m (line 115)
  odearguments(FcnHandlesUsed, solver_name, ode, tspan, y0, options, varargin);

Error in tensegSim (line 35)
    [t,y] = ode45m(@lagTensegrityDynamics,simTime,x0,options,tData);

Error in Ball (line 125)
[t,y] = tensegSim(x0,tEnd,tData,options);
```

System info:
MATLAB R2018b, Ubuntu 18.04 64-bit.

**Comment by vaishnavtv** [comment]
Minor bug. Fixed. Thank you for reporting the issue.

**Comment by vaishnavtv** [comment]
Note that the Arm and Ball are computationally heavy simulations and if the objective is merely a functionality check, the user is advised to keep tEnd (duration of simulation) small or increase tolerances in ODE options.

**Comment by Kevin-Mattheus-Moerman** [comment]
This seems fixed thanks. :+1:
