### ISSUE TITLE
Error in animateTenseg

### ISSUE THREAD

**Issue by apsabelhaus** [uqLab/stedy#7]
An error is thrown in the Template_Dbar.m example, when the video is written using VideoWriter. May be related to #3 .

Error:

Error using VideoWriter/writeVideo (line 344)
Frame must be 912 by 911

Error in animateTenseg (line 95)
    writeVideo(vidObj,im2frame(F.cdata));

Error in Template_DBar (line 153)
animateTenseg(t,y,tData,time_loc,filename,formatSpec,frameRate,AZ, EL,axLims);

I still get a .avi file produced, but it's only got a small number of frames.

A quick google search suggests something like
https://www.mathworks.com/matlabcentral/answers/327160-error-using-videowriter-writevideo-line-344-frame-must-be-434-by-343

For reference, I'm using Ubuntu 18.04 with MATLAB R2017b.

**Comment by apsabelhaus** [comment]
A bit more sleuthing reveals the cause of this error: resizing the window when the movie is being replayed. Error does not occur when window is untouched during replay. Consequently, this isn't technically a bug - the authors could just add a stipulation "don't touch the window until the movie has finished!" or something similar.

**Comment by vaishnavtv** [comment]
I have added a warning dialog box to counter this issue. We hope that suffices.

**Comment by apsabelhaus** [comment]
Yes, that works fine. Just pulled and tested.
